prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    hosts:
      - testpreprod.obadasoussachaddad.fr
    paths:
      - /prometheus(/|$)(.*)
    tls:
      - secretName: lke-monitor-tls
        hosts:
          - testpreprod.obadasoussachaddad.fr
  prometheusSpec:
    routePrefix: /
    externalUrl: https://testpreprod.obadasoussachaddad.fr/prometheus

  service:
    type: ClusterIP

grafana:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    hosts:
      - testpreprod.obadasoussachaddad.fr
    path: /grafana(/|$)(.*)
    tls:
      - secretName: lke-monitor-tls
        hosts:
          - testpreprod.obadasoussachaddad.fr

  grafana.ini:
    server:
      domain: testpreprod.obadasoussachaddad.fr
      root_url: "%(protocol)s://%(domain)s/grafana/"
      enable_gzip: "true"

alertmanager:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    hosts:
      - testpreprod.obadasoussachaddad.fr
    paths:
      - /alertmanager(/|$)(.*)
    tls:
      - secretName: lke-monitor-tls
        hosts:
          - testpreprod.obadasoussachaddad.fr
  alertmanagersSpec:
    routePrefix: /
    externalUrl: https://testpreprod.obadasoussachaddad.fr/alertmanager

# Disable control plane metrics
kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false
