version: '3.1'
services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    restart: always
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${username}
      MONGODB_INITDB_ROOT_PASSWORD: ${password}
      MONGODB_INITDB_DATABASE: morningnews
    ports:
      - 80:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  mongo_exporter:
    image: percona/mongodb_exporter:0.40.0
    restart: always
    environment:
      - MONGODB_URI=mongodb://admin:admin@localhost:80/morningnews
    ports:
      - 9216:9216
      - 17001:1700